site_name: DODAS Apps
theme:
  name: material
  #logo: 'https://github.com/DODAS-TS/dodas-templates/raw/master/logo.png'
  palette:
    primary: "Deep Blue"
    accent: "Light Blue"
nav:
  - Home: "README.md"
  - Quick Start:
    - Spark + Jupyter:
      - Standalone setup: "quick-start.md"
      - Community facility: "quick-start-community.md"
    - HTCondor Cluster:
      - from scratch: "quick-start-htcondor.md"
      - on existing K8s cluster: "quick-start-htcondor-helm.md"
  - From Helm to DODAS template: "from-helm2tosca.md"
repo_name: "dodas-ts/dodas-templates"
repo_url: "https://github.com/DODAS-TS/dodas-templates.git"

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/DODAS-TS'
