site_name: DODAS Apps
theme:
  name: material
  palette:
    primary: "Deep Blue"
    accent: "Light Blue"
nav:
  - Home: "README.md"
  - Overview: "in-depth.md"
  - Quick Start: 
    - Index: "quick-index.md"
    - Configuration:
      - Setup oidc-agent: "setup-oidc.md"
      - Setup DODAS client: "dodas-client.md"
    - Deployment:
      - Using INFN facility: "quick-start-community.md"
      - Standalone setup: "quick-start.md"
  - Supported apps:
    - HTCondor Cluster:
      - Deployment guides:
        - from scratch: "condor.md"
        - on existing K8s cluster: "condor-helm.md"
        - Advanced tips:
          - distributed cluster via flocking: "flocking.md"
          - set WN flavor with ClassAds: "classAds.md"
          - Shared space on WNs:
            - CVMFS: cvmfs.md
            - K8s PersistentVolumes: pv_wn.md
      - User guide: "condor-user.md"
    - Spark + Jupyter:
      - Using INFN facility: "quick-start-community.md"
      - Standalone setup: "quick-start.md"
  - Adopters customization:
    - CMS: "community_cms.md"
    - AMS: "community_ams.md"
    - FERMI: "community_fermi.md"
  #- From Helm to DODAS template: "from-helm2tosca.md"
repo_name: "dodas-ts/dodas-apps"
repo_url: "https://github.com/DODAS-TS/dodas-apps.git"

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/DODAS-TS'
