site_name: DODAS App Templates
theme:
  name: material
  logo:
    icon: cloud_circle
  palette:
    primary: 'Deep Purple'
    accent: 'Green'
nav:
- Home: 'README.md'
repo_name: 'dodas-ts/dodas-templates'
repo_url: 'https://github.com/dodas-ts/dodas-templates'
