site_name: DODAS Apps
theme:
  name: material
  palette:
    primary: "Deep Blue"
    accent: "Light Blue"
nav:
  - Home: "README.md"
  - Overview: "in-depth.md"
  - Quick Start:
    - Setup oidc-agent: "setup-oidc.md"
    - Setup DODAS client: "dodas-client.md"
    - Using INFN facility: "quick-start-community.md"
    - Standalone setup: "quick-start.md"
  - Supported apps:
    - HTCondor Cluster:
      - from scratch: "condor.md"
      - on existing K8s cluster: "condor-helm.md"
    - Spark + Jupyter:
      - Using INFN facility: "quick-start-community.md"
      - Standalone setup: "quick-start.md"
  - Communities:
    - CMS: "community_cms.md"
    - AMS: "community_ams.md"
    - FERMI: "community_fermi.md"
  #- From Helm to DODAS template: "from-helm2tosca.md"
repo_name: "dodas-ts/dodas-templates"
repo_url: "https://github.com/DODAS-TS/dodas-templates.git"

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/DODAS-TS'
