tosca_definitions_version: tosca_simple_yaml_1_0

imports:
  - indigo_custom_types: https://raw.githubusercontent.com/dodas-ts/dodas-templates/master/tosca-types/dodas_custom_apps/spark_type.yml
description: TOSCA template for a complete Spark+Jupyter computing cluster on top of K8s orchestrator

topology_template:

  inputs:

    number_of_masters:
      type: integer
      default: 1

    num_cpus_master: 
      type: integer
      default: 4

    mem_size_master:
      type: string
      default: "8 GB"

    number_of_slaves:
      type: integer
      default: 1 

    num_cpus_slave: 
      type: integer
      default: 4

    mem_size_slave:
      type: string
      default: "8 GB"

    server_image:
      type: string
      #default: "ost://openstack.fisica.unipg.it/cb87a2ac-5469-4bd5-9cce-9682c798b4e4"
      #default: "ost://horizon.cloud.cnaf.infn.it/3d993ab8-5d7b-4362-8fd6-af1391edca39"
      default: "ost://cloud.recas.ba.infn.it/1113d7e8-fc5d-43b9-8d26-61906d89d479"

    helm_values: 
      type: string
      default: |
        externalIp:
          enabled: false
        master:
          image: dodasts/spark-k8s-py:v2.0.0-rc1
          imageTag: v2.0.0-rc1
          jupyter:
            image: dodasts/pyspark-notebook
            tag: v2.0.0-rc1
            

  node_templates:

    helm_install:
      type: tosca.nodes.DODAS.HelmInstall.Spark
      properties:
        name: "spark"
        chart: "dodas/spark"
        repos:
        - { name: dodas, url: "https://dodas-ts.github.io/helm_charts" }
        externalIp: { get_attribute: [ k8s_master_server , public_address, 0 ]  }
        values_file: { get_input: helm_values }
        kubeconfig_path: /etc/kubernetes/admin.conf
      requirements:
        - host: k8s_master_server
        - dependency: k8s_master

    k8s_master:
      type: tosca.nodes.DODAS.FrontEnd.Kubernetes
      properties:
        admin_token: testme
      requirements:
        - host: k8s_master_server

    k8s_slave:
      type: tosca.nodes.DODAS.WorkerNode.Kubernetes
      properties:
        front_end_ip: { get_attribute: [ k8s_master_server, private_address, 0 ] }
      requirements:
        - host: k8s_slave_server

    k8s_master_server:
      type: tosca.nodes.indigo.Compute
      capabilities:
        endpoint:
          properties:
            #network_name: infn-farm.PUBLIC
            network_name: PUBLIC
            ports:
              dashboard:
                protocol: tcp
                source: 30443
              webui:
                protocol: tcp
                source: 30808
              jupyter:
                protocol: tcp
                source: 30888
        scalable:
          properties:
            count: { get_input: number_of_masters }
        host:
          properties:
            #instance_type:  m1.medium
            num_cpus: { get_input: num_cpus_master }
            mem_size: { get_input: mem_size_master } 
        os:
          properties:
            image: { get_input: server_image }

    k8s_slave_server:
      type: tosca.nodes.indigo.Compute
      capabilities:
        endpoint:
          properties:
            #network_name: test-net.PRIVATE
            network_name: PRIVATE
        scalable:
          properties:
            count: { get_input: number_of_slaves }
        host:
          properties:
            #instance_type:  m1.large
            num_cpus: { get_input: num_cpus_slave }
            mem_size: { get_input: mem_size_slave } 
        os:
          properties:
            image: { get_input: server_image }

  outputs:
    k8s_endpoint:
      value: { concat: [ 'https://', get_attribute: [ k8s_master_server, public_address, 0 ], ':30443' ] }
