name: gh_pages

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Gen dummy page
        run: |
          sudo apt-get install -y python3-setuptools
          pip3 install --upgrade pip
          pip3 install mkdocs mkdocs-material
          cp README.md docs/README.md
          mkdocs build --verbose
      -
        name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
